server:
  port: 8080

spring:
  # profile
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379

  # db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;CASE_INSENSITIVE_IDENTIFIERS=true;
    username: sa
    password:

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # auto reload
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

# logging:
  #level:
  #org.hibernate.SQL: debug
 # org.hibernate.type: trace
#  config: classpath:logs/logback-local.xml